In [36]:
import pandas as pd

df = pd.read_csv("customer_credit_risk.csv")

In [37]:
import requests

url = "https://api.worldbank.org/v2/country/IND/indicator/NY.GDP.MKTP.KD.ZG?format=json"

response = requests.get(url)

data = response.json()

print(data)

[{'page': 1, 'pages': 2, 'per_page': 50, 'total': 66, 'sourceid': '2', 'lastupdated': '2026-04-08'}, [{'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2025', 'value': None, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2024', 'value': 6.49476552383821, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2023', 'value': 9.19075493028345, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2022', 'value': 7.60936497768895, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2021', 'value': 9.68959249192875, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2020', 'value': -5.77772470686801, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2019', 'value': 3.87143694070356, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2018', 'value': 6.45385134497769, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2017', 'value': 6.79538341897911, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2016', 'value': 8.25630550179086, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2015', 'value': 7.99625378571471, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2014', 'value': 7.41022760508854, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2013', 'value': 6.38610640094825, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2012', 'value': 5.45638755166587, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2011', 'value': 5.24131619937695, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2010', 'value': 8.49758470221235, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2009', 'value': 7.86188883286074, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2008', 'value': 3.08669805921981, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2007', 'value': 7.6608150670107, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2006', 'value': 8.06073257166651, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2005', 'value': 7.92343062148318, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2004', 'value': 7.92293661199932, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2003', 'value': 7.8603814759073, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2002', 'value': 3.80397532112175, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2001', 'value': 4.82396626555771, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '2000', 'value': 3.84099115659129, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1999', 'value': 8.84575555939531, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1998', 'value': 6.18441582172117, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1997', 'value': 4.04982084998183, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1996', 'value': 7.54952224920051, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1995', 'value': 7.57449183788519, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1994', 'value': 6.65892407028434, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1993', 'value': 4.75077621776924, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1992', 'value': 5.48239602040357, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1991', 'value': 1.05683143496063, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1990', 'value': 5.53345456125301, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1989', 'value': 5.94734333181324, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1988', 'value': 9.62778291607844, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1987', 'value': 3.96535563481719, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1986', 'value': 4.77656416847516, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1985', 'value': 5.25429922311382, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1984', 'value': 3.82073785610604, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1983', 'value': 7.28889290305703, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1982', 'value': 3.47573323969961, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1981', 'value': 6.00620362601497, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1980', 'value': 6.7358215288198, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1979', 'value': -5.23818270446218, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1978', 'value': 5.71253208869331, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1977', 'value': 7.25476458760367, 'unit': '', 'obs_status': '', 'decimal': 1}, {'indicator': {'id': 'NY.GDP.MKTP.KD.ZG', 'value': 'GDP growth (annual %)'}, 'country': {'id': 'IN', 'value': 'India'}, 'countryiso3code': 'IND', 'date': '1976', 'value': 1.66310363813034, 'unit': '', 'obs_status': '', 'decimal': 1}]]

In [39]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('loans.db')
df_sql = pd.read_sql('SELECT * FROM loans;', conn)
conn.close()

print(df_sql.head())

   customer_id  repayment_history  transaction_count  default_flag
0        10001                  1                 45             1
1        10002                  2                 96             0
2        10003                  2                 35             0
3        10004                  1                 47             0
4        10005                  0                109             0

In [31]:
pd.read_json("metadata.json")

,dataset_name,version,source,fields
0,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'customer_id', 'type': 'int', 'descri..."
1,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'age', 'type': 'int', 'description': ..."
2,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'gender', 'type': 'category', 'descri..."
3,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'region', 'type': 'category', 'descri..."
4,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'education_level', 'type': 'ordinal',..."
5,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'employment_type', 'type': 'category'..."
6,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'annual_income', 'type': 'float', 'de..."
7,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'loan_amount', 'type': 'float', 'desc..."
8,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'credit_score', 'type': 'float', 'des..."
9,Customer Credit Risk,1,Synthetic + Multi-source integration,"{'name': 'default_flag', 'type': 'binary', 'de..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   int64
 1   age                4500 non-null   float64
 2   gender             5000 non-null   object
 3   region             5000 non-null   object
 4   education_level    5000 non-null   object
 5   employment_type    4500 non-null   object
 6   annual_income      4500 non-null   float64
 7   loan_amount        5000 non-null   float64
 8   loan_purpose       5000 non-null   object
 9   credit_score       4500 non-null   float64
 10  repayment_history  5000 non-null   int64
 11  transaction_count  5000 non-null   int64
 12  spending_ratio     5000 non-null   float64
 13  join_date          5000 non-null   object
 14  default_flag       5000 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 586.1+ KB

In [6]:
df.describe()

,customer_id,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio,default_flag
count,5000.000000,4500.000000,4.500000e+03,5000.000000,4500.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,42.610667,6.035416e+05,304802.921765,648.471643,2.022000,104.552600,0.503126,0.645800
std,1443.520003,12.557491,2.415042e+05,145297.155932,97.177374,1.438447,54.985179,0.232739,0.478318
min,10001.000000,21.000000,1.000000e+05,50000.000000,318.537475,0.000000,10.000000,0.100093,0.000000
25%,11250.750000,32.000000,4.317292e+05,198067.149418,581.901286,1.000000,56.000000,0.303050,0.000000
50%,12500.500000,43.000000,6.010856e+05,302113.955710,649.720835,2.000000,105.000000,0.499171,1.000000
75%,13750.250000,53.000000,7.689558e+05,404885.131542,714.521647,3.000000,151.000000,0.710434,1.000000
max,15000.000000,64.000000,1.575700e+06,890775.446562,850.000000,9.000000,199.000000,0.899726,1.000000

In [7]:
df.isnull().sum()

customer_id            0
age                  500
gender                 0
region                 0
education_level        0
employment_type      500
annual_income        500
loan_amount            0
loan_purpose           0
credit_score         500
repayment_history      0
transaction_count      0
spending_ratio         0
join_date              0
default_flag           0
dtype: int64

In [9]:
from sklearn.impute import SimpleImputer

num_imp = SimpleImputer(strategy="mean")
df["age"] = num_imp.fit_transform(df[["age"]]).ravel()

cat_imp = SimpleImputer(strategy="most_frequent")
df["employment_type"] = cat_imp.fit_transform(df[["employment_type"]]).ravel()

In [12]:
df["income_missing"] = df["annual_income"].isnull().astype(int)

null_mask = df["annual_income"].isnull()
num_nulls = null_mask.sum()

sampled_values = df["annual_income"].dropna().sample(num_nulls, replace=True)

df.loc[null_mask, "annual_income"] = sampled_values.values

In [13]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors=5)
df[["annual_income","loan_amount","credit_score"]] = knn.fit_transform(
    df[["annual_income","loan_amount","credit_score"]]
)

In [14]:
from scipy import stats

df = df[(np.abs(stats.zscore(df["annual_income"])) < 3)]

In [15]:
Q1 = df["loan_amount"].quantile(0.25)
Q3 = df["loan_amount"].quantile(0.75)
IQR = Q3 - Q1

df = df[(df["loan_amount"] > Q1 - 1.5*IQR) &
        (df["loan_amount"] < Q3 + 1.5*IQR)]

In [16]:
from scipy.stats.mstats import winsorize

df["credit_score"] = winsorize(df["credit_score"], limits=[0.05,0.05])

In [17]:
df["year"] = pd.to_datetime(df["join_date"]).dt.year
df["month"] = pd.to_datetime(df["join_date"]).dt.month
df["weekday"] = pd.to_datetime(df["join_date"]).dt.weekday

In [18]:
edu_map = {"Primary":1,"Secondary":2,"Graduate":3,"Post-Graduate":4}
df["education_level"] = df["education_level"].map(edu_map)

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["gender"] = le.fit_transform(df["gender"])

In [20]:
df = pd.get_dummies(df, columns=["region","loan_purpose"], drop_first=True)

In [21]:
df["income_bin"] = pd.qcut(df["annual_income"], 4, labels=False)

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[["annual_income","loan_amount"]] = scaler.fit_transform(
    df[["annual_income","loan_amount"]]
)

In [23]:
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()
df[["spending_ratio"]] = mm.fit_transform(df[["spending_ratio"]])

In [24]:
df["debt_to_income"] = df["loan_amount"] / df["annual_income"]
df["avg_transactions"] = df["transaction_count"] / 6

In [25]:
import numpy as np

df["log_income"] = np.log1p(df["annual_income"])
df["sqrt_spending"] = np.sqrt(df["spending_ratio"])

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_cols = ["annual_income","loan_amount"]
cat_cols = ["region"]

pipeline = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(), cat_cols)
])

In [ ]:
df.to_csv("final_cleaned_dataset.csv", index=False)